#89, #88, #68, #116
ZerataX/cudacompiler pull request #121
Opened 2020-01-11 17:53 UTC by LukasSiefke

Ist vielleicht wieder ein bisschen viel auf einmal

2020-01-11 18:24 UTC, LukasSiefke commented
Ich könnte noch mal clang format machen..
Wie mache ich das denn?

2020-01-11 18:44 UTC, LukasSiefke commented on CMakeLists.txt
> +        "${PROJECT_SOURCE_DIR}/src/java/yacx/" -d
Das funktioniert noch nicht so ganz :(

2020-01-13 13:13 UTC, LukasSiefke commented on src/jni/Half.cpp
> +    //TODO
Da habe ich wohl noch was vergessen.

2020-01-13 13:59 UTC, LukasSiefke commented on include/yacx/KernelArgs.hpp
> +    void copyDataHtoD() override;
Der Download muss auch noch angepasst werden

2020-01-17 15:17 UTC, LukasSiefke commented
Irgendwie läufts mit den Test von den HalfArgs nicht so richtig. Ich weiß nicht wieso der TestKernel in TestHalfArg nicht kompiliert :(

2020-02-13 14:39 UTC, LukasSiefke commented
Wenn das jetzt noch irgendwer approved kann das auch endlich mal gemergt werden

2020-02-18 12:15 UTC, ZerataX commented on examples/java/ExampleSimpleGemm.java
> +    	int blockDimX = 128;
make format but for java tho

2020-02-18 12:31 UTC, zeratax requested changes

2020-02-18 12:31 UTC, ZerataX commented on src/Kernel.cpp
> +    output = malloc(maxOutputSize);
am liebsten ja smart pointer oder wenn dir das hier zu doof dann new. aber malloc ist nicht so c++ stil.

2020-02-18 12:31 UTC, ZerataX commented on src/Kernel.cpp
> +    free(output);
und dann halt delete

2020-02-18 12:31 UTC, ZerataX commented on src/java/yacx/PaddingArg.java
> +				paddingValue, (int) arg.getSizeBytes());
hmmmmm :/

2020-02-18 12:43 UTC, ZerataX commented
das würde dann sogar https://github.com/rise-lang/executor/issues/6 beinhalten ^^

2020-02-18 12:51 UTC, zeratax approved these changes

2020-02-18 12:52 UTC, merged