Fertigstellung_Example
ZerataX/cudacompiler pull request #164
Opened 2020-04-18 02:44 UTC by felixling94

Hier wird ein nachgebessertes Beispiel zum CUDA-Executor erstellt.

2020-04-18 02:51 UTC, zeratax requested changes
this is mostly very clean and easy to understand. really well done, pretty much just effective bandwith usage has changed otherwise LGTM

2020-04-18 02:51 UTC, ZerataX commented on examples/example_matrix_multiply.cpp
> +              << yacx::effective_bandwidth(time.launch, args.size()) << " GB/s\n";
https://github.com/ZerataX/yacx/blob/master/include/yacx/KernelTime.hpp#L20
these are now best used directly as functions of KernelTime

2020-04-18 02:51 UTC, ZerataX commented on examples/example_sumArray.cpp
> +      rhs_string=std::to_string(rhs[i]);
I don't think this is necessary? I think << will cast an int to a string stream anyways?

2020-04-18 02:51 UTC, ZerataX commented on examples/example_sumArray.cpp
> +              << yacx::effective_bandwidth(time.launch,  args.size()) << " GB/s\n";
again use the kerneltime function

2020-04-18 17:44 UTC, zeratax approved these changes
wow this looks stellar!

2020-04-19 00:33 UTC, felixling94 commented
Es wäre gut, wenn einer von euch Abhilfe zur Einbindung an fremde Header-Datei finden könntest, da ich Schwierigkeit damit habe.

2020-04-28 02:14 UTC, merged